language: java
jdk: oraclejdk8
sudo: required

branches:
only: develop

before_install:
 - chmod +x gradlew

before_script:
  - wget http://services.gradle.org/distributions/gradle-3.5.1-bin.zip
  - unzip gradle-3.5.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.5.1
  - export PATH=$GRADLE_HOME/bin:$PATH

script: gradle check

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
  recipients: marcos.x86@outlook.com
